stages:
  - test
  - build

test:
  stage: test
  image: python:3.7
  before_script:
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install -r requirements-dev.txt
  script:
    - make test
    - make lint
    - make type-check

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --update --no-cache python3
    - apk add --update --no-cache py3-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  only:
    - primary
  tags:
    - docker
