#!/usr/bin/env bash
set -e -o pipefail

base=$(cd "$(dirname "$0")" && pwd -P)

cd "$base"
. ./activate -q

pytest -q "$@"
echo -e "\r"

flake=$(flake8 --exit-zero --exclude=__pycache__,venv)
[[ -z $flake ]] && echo -e 'Style checks pass\n' \
  || { echo -e "Style check errors:\n$flake"; exit 1; }

echo All tests pass
